src/Entity/Measurement.php
<?php

namespace App\Entity;

use App\Repository\MeasurementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MeasurementRepository::class)]
class Measurement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'measurements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $measure_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $create_date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $celsius = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getMeasureDate(): ?\DateTimeInterface
    {
        return $this->measure_date;
    }

    public function setMeasureDate(\DateTimeInterface $measure_date): static
    {
        $this->measure_date = $measure_date;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): static
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getCelsius(): ?string
    {
        return $this->celsius;
    }

    public function setCelsius(string $celsius): static
    {
        $this->celsius = $celsius;

        return $this;
    }
}

src/Form/MeasurementType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\Measurement;
use phpDocumentor\Reflection\Types\Float_;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MeasurementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('measure_date')
            ->add('create_date')
            ->add('celsius',null, [
                'attr' => [
                    'placeholder' => 'Enter number of celsius',
                ]
            ])
            ->add('location', EntityType::class, [
                'class' => Location::class,
'choice_label' => 'city',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Measurement::class,
        ]);
    }
}

src/Controller/MeasurementController.php
<?php

namespace App\Controller;

use App\Entity\Measurement;
use App\Form\MeasurementType;
use App\Repository\MeasurementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/measurement')]
class MeasurementController extends AbstractController
{
    #[IsGranted('ROLE_MEASUREMENT_INDEX')]
    #[Route('/', name: 'app_measurement_index', methods: ['GET'])]
    public function index(MeasurementRepository $measurementRepository): Response
    {
        return $this->render('measurement/index.html.twig', [
            'measurements' => $measurementRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_MEASUREMENT_NEW')]
    #[Route('/new', name: 'app_measurement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $measurement = new Measurement();
        $form = $this->createForm(MeasurementType::class, $measurement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($measurement);
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measurement/new.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_MEASUREMENT_SHOW')]
    #[Route('/{id}', name: 'app_measurement_show', methods: ['GET'])]
    public function show(Measurement $measurement): Response
    {
        return $this->render('measurement/show.html.twig', [
            'measurement' => $measurement,
        ]);
    }

    #[IsGranted('ROLE_MEASUREMENT_EDIT')]
    #[Route('/{id}/edit', name: 'app_measurement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MeasurementType::class, $measurement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measurement/edit.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_MEASUREMENT_DELETE')]
    #[Route('/{id}', name: 'app_measurement_delete', methods: ['POST'])]
    public function delete(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$measurement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($measurement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/measurement/_delete_form.html.twig
<form method="post" action="{{ path('app_measurement_delete', {'id': measurement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ measurement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/measurement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/measurement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Measurement{% endblock %}

{% block body %}
    <h1>Edit Measurement</h1>

    {{ include('measurement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}

templates/measurement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement index{% endblock %}

{% block body %}
    <h1>Measurement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Measure_date</th>
                <th>Create_date</th>
                <th>Celsius</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for measurement in measurements %}
            <tr>
                <td>{{ measurement.id }}</td>
                <td>{{ measurement.measureDate ? measurement.measureDate|date('Y-m-d') : '' }}</td>
                <td>{{ measurement.createDate ? measurement.createDate|date('Y-m-d') : '' }}</td>
                <td>{{ measurement.celsius }}</td>
                <td>
                    {% if is_granted('ROLE_MEASUREMENT_SHOW') %}
                        <a href="{{ path('app_measurement_show', {'id': measurement.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_MEASUREMENT_EDIT') %}
                        <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_MEASUREMENT_NEW') %}
        <a href="{{ path('app_measurement_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/measurement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Measurement{% endblock %}

{% block body %}
    <h1>Create new Measurement</h1>

    {{ include('measurement/_form.html.twig') }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>
{% endblock %}

templates/measurement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement{% endblock %}

{% block body %}
    <h1>Measurement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ measurement.id }}</td>
            </tr>
            <tr>
                <th>Measure_date</th>
                <td>{{ measurement.measureDate ? measurement.measureDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Create_date</th>
                <td>{{ measurement.createDate ? measurement.createDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Celsius</th>
                <td>{{ measurement.celsius }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_measurement_index') }}">back to list</a>

    <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}